default_rancherimportcluster_api_token: '{{ "sampletoken" }}'
default_rancherimportcluster_rancher_host:  '{{ "samplehost" }}'
default_rancherimportcluster_cluster_name: '{{ "sampleclustername" }}'

default_rancherimportcluster_api_token: '{{ RANCHERIMPORTCLUSTER_API_TOKEN | default(default_rancherimportcluster_api_token) }}'
default_rancherimportcluster_rancher_host: '{{ RANCHERIMPORTCLUSTER_RANCHER_HOST | default(default_rancherimportcluster_rancher_host) }}'
default_rancherimportcluster_cluster_name: '{{ RANCHER_CLUSTER_NAME | default(default_rancherimportcluster_cluster_name) }}'

default_rke2installation_script_url:  'https://get.rke2.io' 
default_importrke2_to_rancher: true
default_rke2_os_hardening: true
default_rke2_version: 'v1.30.5+rke2r1'
default_rke2_cni: 'cilium'
default_rke2_token: 'ExAmPlET0kEn'


default_rancherimportcluster_create_yaml:
  apiVersion: provisioning.cattle.io/v1
  kind: Cluster
  metadata:
    name: "{{ default_rancherimportcluster_cluster_name }}"
    annotations:
      {}
    labels:
      {}
    namespace: fleet-default
  spec:
  __clone: true
